apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:

      containers:
        - name: frontend
          image: ghcr.io/pasokatazip/frontend:3145ce36e1124883bfb35cbb7bc62e99c232746a

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: frontend-config
