apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:

      containers:
        - name: frontend
          image: ghcr.io/pasokatazip/frontend:39b283656e379da7712576cf7fced59005522df8

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: frontend-config
