apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:

      containers:
        - name: frontend
          image: ghcr.io/pasokatazip/frontend:041d10745e9067a79ee2e296370f33f15f1fbdf2

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: frontend-config
