apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      #imagePullSecrets:
        #- name: ghcr-secret

      containers:
        - name: backend
          image: ghcr.io/pasokatazip/backend:4269d43523bbaa59ffb32605127cf2b9bd0220fe

          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-secret
