apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      #imagePullSecrets:
        #- name: ghcr-secret

      containers:
        - name: backend
          image: ghcr.io/pasokatazip/backend:859cc7451af38e45db80d36ea9e5e4f00743e0c1

          ports:
            - containerPort: 8080

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL