apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      #imagePullSecrets:
        #- name: ghcr-secret

      containers:
        - name: backend
          image: ghcr.io/pasokatazip/backend:2ca702b27419074fbdbc3bd226d32f3447a55c53

          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-secret
