apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
  namespace: app
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/pasokatazip/backend:3c83f244e72a4022cd588865830e4ea09c247dd8
          command:
            - goose
            - -dir
            - migrations
            - postgres
            - "$(DATABASE_URL)"
            - up
          envFrom:
            - secretRef:
                name: backend-secret
