apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
  namespace: app
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/pasokatazip/backend:56c030aed4f8f63df202a80e8469df2b34b26664
          command:
            - goose
            - -dir
            - migrations
            - postgres
            - "$(DATABASE_URL)"
            - up
          envFrom:
            - secretRef:
                name: backend-secret
