apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  namespace: app
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/pasokatazip/backend:2ca702b27419074fbdbc3bd226d32f3447a55c53
          command:
            - goose
            - -dir
            - migrations
            - postgres
            - "$(DATABASE_URL)"
            - up
          envFrom:
            - secretRef:
                name: backend-secret
