apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-python-worker
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-python-worker
  template:
    metadata:
      labels:
        app: backend-python-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/pasokatazip/backend-python:a18a8df243d5f6452d42403757b71fbdfbc0f1fe
          envFrom:
            - secretRef:
                name: backend-secret
          env:
            - name: HF_HOME
              value: /cache/huggingface
          volumeMounts:
            - name: model-cache
              mountPath: /cache/huggingface
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: hf-model-cache
